=== raml-apis/HealthCare/schemas/glossaryPage-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "categories" : {
      "type" : "array" ,
      "required" : false ,
      "items" : 
        {
          "type" : "string"
        }
      
    } ,
    "layout" : {
      "type" : "string" ,
      "required" : false
    } ,
    "published" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "title" : {
      "type" : "string" ,
      "required" : false
    } ,
    "lang" : {
      "type" : "string" ,
      "required" : false
    } ,
    "tags" : {
      "type" : "array" ,
      "required" : false ,
      "items" : 
        {
          "type" : "string"
        }
      
    } ,
    "url" : {
      "type" : "string" ,
      "required" : false
    } ,
    "content" : {
      "type" : "string" ,
      "required" : false
    } ,
    "date" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sort" : {
      "type" : "number" ,
      "required" : false
    } ,
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "excerpt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "path" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/HealthCare/examples/glossaryPage-example.json
{
  "categories" : [
    "glossary"
  ] ,
  "layout" : "glossary-word" ,
  "published" : true ,
  "title" : "Modified Adjusted Gross Income (MAGI)" ,
  "lang" : "en" ,
  "tags" : [
    "glossary"
  ] ,
  "url" : "/glossary/modified-adjusted-gross-income-magi" ,
  "content" : "<p>The figure used to determine eligibility for lower costs in the Marketplace and for Medicaid and CHIP. Generally, modified adjusted gross income is your adjusted gross income plus any tax-exempt Social Security, interest, or foreign income you have.</p>\r\n" ,
  "date" : "2013-07-08 00:00:00 -0400" ,
  "sort" : 0 ,
  "id" : "/glossary/modified-adjusted-gross-income-magi" ,
  "excerpt" : "<p>The figure used to determine eligibility for lower costs in the Marketplace and for Medicaid and CHIP. Generally, modified adjusted gross income is your adjusted gross income plus any tax-exempt Social Security, interest, or foreign income you have.</p>\r\n" ,
  "path" : "_posts/glossary/2013-07-08-modified-adjusted-gross-income-magi.md"
}
