=== raml-apis/HealthCare/schemas/questionPage-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "categories" : {
      "type" : "array" ,
      "required" : false ,
      "items" : 
        {
          "type" : "string"
        }
      
    } ,
    "tags" : {
      "type" : "array" ,
      "required" : false ,
      "items" : 
        {
          "type" : "string"
        }
      
    } ,
    "published" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "title" : {
      "type" : "string" ,
      "required" : false
    } ,
    "lang" : {
      "type" : "string" ,
      "required" : false
    } ,
    "url" : {
      "type" : "string" ,
      "required" : false
    } ,
    "content" : {
      "type" : "string" ,
      "required" : false
    } ,
    "date" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sort" : {
      "type" : "number" ,
      "required" : false
    } ,
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "excerpt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "path" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/HealthCare/examples/questionPage-example.json
{
  "categories" : [
    "question"
  ] ,
  "tags" : [
    "question"
  ] ,
  "published" : true ,
  "title" : "Do Marketplace plans cover breastfeeding and contraception benefits?  " ,
  "lang" : "en" ,
  "url" : "/question/do-marketplace-plans-cover-breastfeeding-and-contraception-benefits" ,
  "content" : "<p>Generally, yes. Learn more about <a href=\"/what-are-my-breastfeeding-benefits/\">breastfeeding</a> and <a href=\"/what-are-my-birth-control-benefits/\">contraception</a> benefits under the health care law.</p>\r\n" ,
  "date" : "2014-01-29 00:00:00 -0500" ,
  "sort" : 0 ,
  "id" : "/question/do-marketplace-plans-cover-breastfeeding-and-contraception-benefits" ,
  "excerpt" : "<p>Generally, yes. Learn more about <a href=\"/what-are-my-breastfeeding-benefits/\">breastfeeding</a> and <a href=\"/what-are-my-birth-control-benefits/\">contraception</a> benefits under the health care law.</p>\r\n" ,
  "path" : "_posts/questions/2014-01-29-do-marketplace-plans-cover-breastfeeding-and-contraception-benefits.md"
}
